load('config.js');
function execute() {
    return Response.success([
        {title: "Webtoon", input: BASE_URL + "/the-loai/webtoon", script: "gen.js"},
        {title: "Xuyên Không", input: BASE_URL + "/the-loai/xuyen-khong", script: "gen.js"},
        {title: "Xuyên Nhanh", input: BASE_URL + "/the-loai/xuyen-nhanh", script: "gen.js"},
        {title: "Yaoi", input: BASE_URL + "/the-loai/yaoi", script: "gen.js"},
        {title: "16+", input: BASE_URL + "/the-loai/16", script: "gen.js"},
        {title: "18+", input: BASE_URL + "/the-loai/18", script: "gen.js"},
        {title: "ABO", input: BASE_URL + "/the-loai/abo", script: "gen.js"},
        {title: "Action", input: BASE_URL + "/the-loai/action", script: "gen.js"},
        {title: "Adult", input: BASE_URL + "/the-loai/adult", script: "gen.js"},
        {title: "Adventure", input: BASE_URL + "/the-loai/adventure", script: "gen.js"},
        {title: "Ahegao", input: BASE_URL + "/the-loai/ahegao", script: "gen.js"},
        {title: "Anime", input: BASE_URL + "/the-loai/anime", script: "gen.js"},
        {title: "Bách Hợp", input: BASE_URL + "/the-loai/bach-hop", script: "gen.js"},
        {title: "Bị thuốc", input: BASE_URL + "/the-loai/bi-thuoc", script: "gen.js"},
        {title: "Boy Love", input: BASE_URL + "/the-loai/boy-love", script: "gen.js"},
        {title: "BoyLove", input: BASE_URL + "/the-loai/boylove", script: "gen.js"},
        {title: "Chuyển Sinh", input: BASE_URL + "/the-loai/chuyen-sinh", script: "gen.js"},
        {title: "Cổ Đại", input: BASE_URL + "/the-loai/co-dai", script: "gen.js"},
        {title: "Cổ Trang", input: BASE_URL + "/the-loai/co-trang", script: "gen.js"},
        {title: "Comedy", input: BASE_URL + "/the-loai/comedy", script: "gen.js"},
        {title: "Comic", input: BASE_URL + "/the-loai/comic", script: "gen.js"},
        {title: "Cooking", input: BASE_URL + "/the-loai/cooking", script: "gen.js"},
        {title: "Đam Mỹ", input: BASE_URL + "/the-loai/dam-my", script: "gen.js"},
        {title: "Đô Thị", input: BASE_URL + "/the-loai/do-thi", script: "gen.js"},
        {title: "Doujinshi", input: BASE_URL + "/the-loai/doujinshi", script: "gen.js"},
        {title: "Drama", input: BASE_URL + "/the-loai/drama", script: "gen.js"},
        {title: "Ecchi", input: BASE_URL + "/the-loai/ecchi", script: "gen.js"},
        {title: "Echi", input: BASE_URL + "/the-loai/echi", script: "gen.js"},
        {title: "Fantasy", input: BASE_URL + "/the-loai/fantasy", script: "gen.js"},
        {title: "Full Trọn Bộ", input: BASE_URL + "/the-loai/full-tron-bo", script: "gen.js"},
        {title: "Game", input: BASE_URL + "/the-loai/game", script: "gen.js"},
        {title: "Gender Bender", input: BASE_URL + "/the-loai/gender-bender", script: "gen.js"},
        {title: "Giới giải trí", input: BASE_URL + "/the-loai/gioi-giai-tri", script: "gen.js"},
        {title: "Girl Love", input: BASE_URL + "/the-loai/girl-love", script: "gen.js"},
        {title: "GirlLove", input: BASE_URL + "/the-loai/girllove", script: "gen.js"},
        {title: "Hài hước", input: BASE_URL + "/the-loai/hai-huoc", script: "gen.js"},
        {title: "Hành Động", input: BASE_URL + "/the-loai/hanh-dong", script: "gen.js"},
        {title: "Harem", input: BASE_URL + "/the-loai/harem", script: "gen.js"},
        {title: "Hệ Thống", input: BASE_URL + "/the-loai/he-thong", script: "gen.js"},
        {title: "Hentai", input: BASE_URL + "/the-loai/hentai", script: "gen.js"},
        {title: "Hiện đại", input: BASE_URL + "/the-loai/hien-dai", script: "gen.js"},
        {title: "Hiện Thực", input: BASE_URL + "/the-loai/hien-thuc", script: "gen.js"},
        {title: "Historical", input: BASE_URL + "/the-loai/historical", script: "gen.js"},
        {title: "Học Đường", input: BASE_URL + "/the-loai/hoc-duong", script: "gen.js"},
        {title: "Horror", input: BASE_URL + "/the-loai/horror", script: "gen.js"},
        {title: "Huyền Huyễn", input: BASE_URL + "/the-loai/huyen-huyen", script: "gen.js"},
        {title: "Isekai", input: BASE_URL + "/the-loai/isekai", script: "gen.js"},
        {title: "Josei", input: BASE_URL + "/the-loai/josei", script: "gen.js"},
        {title: "Kịch Tính", input: BASE_URL + "/the-loai/kich-tinh", script: "gen.js"},
        {title: "Kinh dị", input: BASE_URL + "/the-loai/kinh-di", script: "gen.js"},
        {title: "Lãng Mạn", input: BASE_URL + "/the-loai/lang-man", script: "gen.js"},
        {title: "Linh Dị", input: BASE_URL + "/the-loai/linh-di", script: "gen.js"},
        {title: "Live action", input: BASE_URL + "/the-loai/live-action", script: "gen.js"},
        {title: "Magic", input: BASE_URL + "/the-loai/magic", script: "gen.js"},
        {title: "MANGA", input: BASE_URL + "/the-loai/manga", script: "gen.js"},
        { title: "Manhua", input: "/the-loai/manhua", script: "gen.js" },
        { title: "Manhwa", input: "/the-loai/manhwa", script: "gen.js" },
        { title: "Mạo Hiểm", input: "/the-loai/mao-hiem", script: "gen.js" },
        { title: "Martial Arts", input: "/the-loai/martial-arts", script: "gen.js" },
        { title: "Mature", input: "/the-loai/mature", script: "gen.js" },
        { title: "Mecha", input: "/the-loai/mecha", script: "gen.js" },
        { title: "Mystery", input: "/the-loai/mystery", script: "gen.js" },
        { title: "Ngôn Tình", input: "/the-loai/ngon-tinh", script: "gen.js" },
        { title: "Ngược", input: "/the-loai/nguoc", script: "gen.js" },
        { title: "Người Thú", input: "/the-loai/nguoi-thu", script: "gen.js" },
        { title: "Niên Hạ", input: "/the-loai/nien-ha", script: "gen.js" },
        { title: "NTR", input: "/the-loai/ntr", script: "gen.js" },
        { title: "One shot", input: "/the-loai/one-shot", script: "gen.js" },
        { title: "Oneshot", input: "/the-loai/oneshot", script: "gen.js" },
        { title: "Paizuri", input: "/the-loai/paizuri", script: "gen.js" },
        { title: "Phiêu Lưu", input: "/the-loai/phieu-luu", script: "gen.js" },
        { title: "Psychological", input: "/the-loai/psychological", script: "gen.js" },
        { title: "Romance", input: "/the-loai/romance", script: "gen.js" },
        { title: "School Life", input: "/the-loai/school-life", script: "gen.js" },
        { title: "Schoolgirl Uniform", input: "/the-loai/schoolgirl-uniform", script: "gen.js" },
        { title: "Sci-fi", input: "/the-loai/sci-fi", script: "gen.js" },
        { title: "Seinen", input: "/the-loai/seinen", script: "gen.js" },
        { title: "Shoujo", input: "/the-loai/shoujo", script: "gen.js" },
        { title: "Shoujo Ai", input: "/the-loai/shoujo-ai", script: "gen.js" },
        { title: "Shounen", input: "/the-loai/shounen", script: "gen.js" },
        { title: "Shounen ai", input: "/the-loai/shounen-ai", script: "gen.js" },
        { title: "Showbiz", input: "/the-loai/showbiz", script: "gen.js" },
        { title: "Slice of Life", input: "/the-loai/slice-of-life", script: "gen.js" },
        { title: "Smut", input: "/the-loai/smut", script: "gen.js" },
        { title: "Soft Yaoi", input: "/the-loai/soft-yaoi", script: "gen.js" },
        { title: "Soft Yuri", input: "/the-loai/soft-yuri", script: "gen.js" },
        { title: "Sports", input: "/the-loai/sports", script: "gen.js" },
        { title: "Stockings", input: "/the-loai/stockings", script: "gen.js" },
        { title: "Sủng", input: "/the-loai/sung", script: "gen.js" },
        { title: "Supernatural", input: "/the-loai/supernatural", script: "gen.js" },
        { title: "Thần Ma", input: "/the-loai/than-ma", script: "gen.js" },
        { title: "Thiếu Nhi", input: "/the-loai/thieu-nhi", script: "gen.js" },
        { title: "Tiên Hiệp", input: "/the-loai/tien-hiep", script: "gen.js" },
        { title: "Tình Cảm", input: "/the-loai/tinh-cam", script: "gen.js" },
        { title: "Tragedy", input: "/the-loai/tragedy", script: "gen.js" },
        { title: "Trinh Thám", input: "/the-loai/trinh-tham", script: "gen.js" },
        { title: "Trọng sinh", input: "/the-loai/trong-sinh", script: "gen.js" },
        { title: "Truyện dài", input: "/the-loai/truyen-dai", script: "gen.js" },
        { title: "Truyện Màu", input: "/the-loai/truyen-mau", script: "gen.js" },
        { title: "Truyện ngắn", input: "/the-loai/truyen-ngan", script: "gen.js" },
        { title: "Truyện tranh", input: "/the-loai/truyen-tranh", script: "gen.js" },
        { title: "Truyện tranh 16+", input: "/the-loai/truyen-tranh-16", script: "gen.js" },
        { title: "Truyện tranh 18+", input: "/the-loai/truyen-tranh-18", script: "gen.js" },
        { title: "Tu Tiên", input: "/the-loai/tu-tien", script: "gen.js" },
        { title: "Vếu to", input: "/the-loai/veu-to", script: "gen.js" },
        { title: "Võ hiệp", input: "/the-loai/vo-hiep", script: "gen.js" },
        { title: "Võ hiệp", input: "/the-loai/vo-hiep", script: "gen.js" },
        { title: "vườn trường", input: "/the-loai/vuon-truong", script: "gen.js" },
        { title: "Webtoon", input: "/the-loai/webtoon", script: "gen.js" }
    ]);
}